services:

  nginx:
    container_name: nginx
    build: containers/nginx
    restart: always
    env_file:
      - containers/nginx/.env
    ports:
      - 443:443
    networks:
      - transcendence
    volumes:
      - frontend:/var/www/html
    depends_on:
      - nodejs

  nodejs:
    container_name: nodejs
    build: containers/nodejs
    restart: always
    networks:
      - transcendence
    volumes:
      - backend:/backend

volumes:

  frontend:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./frontend

  backend:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./backend

networks:
  transcendence: {}
