services:

  nginx:
    container_name: nginx
    build: containers/nginx
    restart: always
    env_file:
      - containers/nginx/.env
    ports:
      - ${PORT:-443}:443
    networks:
      - transcendence
    volumes:
      - frontend:/var/www
    depends_on:
      - nodejs

  nodejs:
    container_name: nodejs
    build: containers/nodejs
    restart: always
    networks:
      - transcendence
    volumes:
      - backend:/backend
  sqlitebrowser:
    container_name: sqlitebrowser
    build: containers/sqlitebrowser
    ports:
      - "3001:3000"
    depends_on:
      - nodejs
    volumes:
      - backend:/backend
    
volumes:

  frontend:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./frontend

  backend:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./backend

networks:
  transcendence: {}
