services:

  nginx:
    container_name: nginx
    build: containers/nginx
    restart: always
    env_file:
      - containers/nginx/.env
    ports:
      - 443:443
    networks:
      - transcendence
    depends_on:
      - nodejs

  nodejs:
    container_name: nodejs
    build: containers/nodejs
    restart: always
    networks:
      - transcendence

networks:
  transcendence: {}
